# Generated by Django 3.0.3 on 2020-04-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
