# Generated by Django 3.0.3 on 2020-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.ManyToManyField(to='feed.Artist')),
            ],
        ),
    ]
