# Generated by Django 3.0.3 on 2020-04-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_releasesearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseSearch',
        ),
    ]
