# Generated by Django 3.0.3 on 2020-04-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_delete_releasesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(to='feed.Artist')),
            ],
        ),
    ]
