# Generated by Django 3.0.3 on 2020-04-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_artistgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistgroup',
            name='artists',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtistGroup',
        ),
    ]
