# Generated by Django 3.0.3 on 2020-04-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_artist_artist_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_groups',
        ),
    ]
