# Generated by Django 3.0.3 on 2020-04-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_artist_artist_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_groups',
            field=models.ManyToManyField(to='feed.ArtistGroup'),
        ),
    ]
