# Generated by Django 3.0.3 on 2020-04-12 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('spotify_profile_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('artists', models.ManyToManyField(to='feed.Artist')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_groups',
            field=models.ManyToManyField(to='feed.ArtistGroup'),
        ),
    ]
